# Generated by Django 4.2.14 on 2024-07-10 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("travelapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="itinerary",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="diningoption",
            name="itinerary",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="travelapp.itinerary"
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="itinerary",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="travelapp.itinerary"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="itinerary",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="travelapp.itinerary"
            ),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="itinerary",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="travelapp.itinerary"
            ),
        ),
    ]
